In [3]:
L = [1, 2, 3]

In [4]:
L.insert?

In [5]:
L?

In [6]:
def square(a):
    """Return the square of a"""
    return a ** 2

In [7]:
square?

In [8]:
square??

In [9]:
len??

In [2]:
%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


In [3]:
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
    return total

In [5]:
%lprun -f sum_of_lists(5000)

G:\Anaconda3\lib\site-packages\line_profiler.py:321: UserWarning: Could not extract a code object for the object 52923312
  profile = LineProfiler(*funcs)


In [6]:
%lprun -f sum_of_lists sum_of_lists(5000)

In [7]:
%load_ext memory_profiler

In [8]:
%memit sum_of_lists(100000)

peak memory: 55.76 MiB, increment: 6.49 MiB


In [9]:
%%file mprun_demo.py
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
        del L "Delete link to L"
    return total

Writing mprun_demo.py


In [10]:
from mprun_demo import sum_of_lists
%mprun -f sum_of_lists sum_of_lists(1000000)

SyntaxError: invalid syntax (mprun_demo.py, line 6)

In [11]:
%%file mprun_demo.py
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
        del L # Delete link to L
    return total

Overwriting mprun_demo.py


In [12]:
%mprun -f sum_of_lists sum_of_lists(1000000)

ERROR: Could not find file <ipython-input-3-f105717832a2>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.



In [14]:
from mprun_demo import sum_of_lists
%mprun -f sum_of_lists sum_of_lists(1000000)

*** KeyboardInterrupt exception caught in code being profiled.


In [1]:
import numpy as np

In [8]:
x = np.linspace(0, 5, 5)
y = np.linspace(0, 5, 5)[:, np.newaxis]

In [9]:
x

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [10]:
y

array([[0.  ],
       [1.25],
       [2.5 ],
       [3.75],
       [5.  ]])

In [11]:
y * x

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  1.5625,  3.125 ,  4.6875,  6.25  ],
       [ 0.    ,  3.125 ,  6.25  ,  9.375 , 12.5   ],
       [ 0.    ,  4.6875,  9.375 , 14.0625, 18.75  ],
       [ 0.    ,  6.25  , 12.5   , 18.75  , 25.    ]])

In [12]:
x * y

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  1.5625,  3.125 ,  4.6875,  6.25  ],
       [ 0.    ,  3.125 ,  6.25  ,  9.375 , 12.5   ],
       [ 0.    ,  4.6875,  9.375 , 14.0625, 18.75  ],
       [ 0.    ,  6.25  , 12.5   , 18.75  , 25.    ]])

In [17]:
np.random.randn?

In [19]:
rand = np.random.RandomState(42)

In [21]:
X = rand.rand(10, 2)
X

array([[0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041],
       [0.60754485, 0.17052412],
       [0.06505159, 0.94888554],
       [0.96563203, 0.80839735],
       [0.30461377, 0.09767211],
       [0.68423303, 0.44015249]])

In [40]:
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a.shape

(3, 4)

In [42]:
b = a[:, np.newaxis, :]
b

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [43]:
b.shape

(3, 1, 4)

In [45]:
c = a[np.newaxis, :, :]
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [46]:
c.shape

(1, 3, 4)

In [47]:
d = a[:, :, np.newaxis]
d

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [48]:
d.shape

(3, 4, 1)

In [51]:
%matplotlib inline
import matplotlib.pyplot as plt

In [52]:
plt.plot?